### ISSUE TITLE
Nginx Proxy Manager 用阿里域名申请证书你解决了么

### ISSUE THREAD

**Issue by Saner0** [sanduo-656/feishu-chatgpt#1]
我也同样遇到了这个问题，请问下你怎么解决的

**Comment by sanduo-656** [comment]
解决了，但是获取的时候要翻墙。还有一种做法就是在dns中写入那个ssl证书机构的识别码，就不需要翻墙那么麻烦了
https://letsencrypt.org/zh-cn/docs/challenge-types/#dns-01-%E9%AA%8C%E8%AF%81
sanduo.xi
***@***.***
---- 回复的原邮件 ----
***@***.***>发送日期2024年7月28日 ***@***.***>***@***.***>主题[sanduo-656/feishu-chatgpt] Nginx Proxy Manager 用阿里域名申请证书你解决了么 (Issue #1)
我也同样遇到了这个问题，请问下你怎么解决的

**Comment by Saner0** [comment]
能留个联系方式么 这个我没解决，请教下你
